### ISSUE TITLE
Don't run any of the EEPROM tools if not running on a Pi4 or Pi5

### ISSUE THREAD

**Issue by lurch** [raspberrypi/rpi-update#27]
I just ran `rpi-update` on a Raspberry Pi 3B+, and in the middle of the output it says:
```
This tool only works with Raspberry Pi4 and Rapberry Pi5
```

I believe this is a harmless error message from `rpi-eeprom-update`, but people might get confused by that message, and think that `rpi-update` itself isn't working on platforms other than Pi4 or Pi5?

**Comment by timg236** [comment]
That message would be from rpi-eeprom-update (but an old version) which has changed already

**Comment by lurch** [comment]
Yup, when I run `rpi-update` on a Raspberry Pi 3B+ the message _now_ says:
```
Device does not have a Raspberry Pi bootloader EEPROM (e.g. Pi 4 or Pi 5). Skipping bootloader update.
```
which is **much** clearer. Thanks!
